name: Build nonebot-all4one image

on: workflow_dispatch

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Get nonebot-all4one version
        id: get-version
        shell: python
        run: |
          import tomllib
          with open("nonebot-all4one/pyproject.toml", "rb") as f:
              data = tomllib.load(f)
          version = data["tool"]["poetry"]["version"]
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"version={version}\n")

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Tags
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/he0119/nonebot-all4one
          tags: |
            latest
            ${{ steps.get-version.outputs.version }}

      - name: Build and Publish
        uses: docker/build-push-action@v3
        with:
          context: nonebot-all4one
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
