name: Build nonebot-all4one image

on: workflow_dispatch

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Fecth latest nonebot-all4one version
        id: fetch-nonebot-all4one
        run: |
          cd nonebot-all4one
          python -m pip install --user pipx
          python -m pipx run --no-cache poetry export -f requirements.txt --output requirements.txt --without-hashes
          python -m pipx run --no-cache nb-cli generate -f bot.py
          VERSION=$(grep -Po "nonebot-plugin-all4one==\K.+(?= ;)" requirements.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Tags
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/he0119/nonebot-all4one
          tags: |
            latest
            ${{ steps.fetch-nonebot-all4one.outputs.version }}

      - name: Build and Publish
        uses: docker/build-push-action@v3
        with:
          context: nonebot-all4one
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
